import { useState } from 'react';

export default function Ticket() {
  const [input, setInput] = useState('');
  const [result, setResult] = useState('');

  const handleTicketSubmit = async () => {
    if (!input.trim()) {
      setResult('⚠️ Please enter an incident description.');
      return;
    }

    try {
      const res = await fetch('https://third-space-backend.onrender.com/api/ticket', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ incident: input }),
      });

      const data = await res.json();
      setResult(data.result || '❌ No ticket returned.');
    } catch (error) {
      console.error("❌ Ticket generation error:", error);
      setResult('❌ Could not generate ticket.');
    }
  };

  return (
    <div style={{ padding: '1rem' }}>
      <h2>🎫 Ticket Generator</h2>

      <textarea
        value={input}
        onChange={(e) => setInput(e.target.value)}
        placeholder="Describe the incident here..."
        rows={4}
        style={{ width: '100%', maxWidth: '500px', marginBottom: '10px' }}
      />
      <br />
      <button onClick={handleTicketSubmit}>Generate Ticket</button>

      <div style={{ marginTop: '1rem', whiteSpace: 'pre-wrap' }}>
        <strong>Generated Ticket:</strong>
        <p>{result}</p>
        {result && (
          <p style={{ fontSize: '0.85em', color: 'gray' }}>
            💡 Generated by AI — review before submission.
          </p>
        )}
      </div>
    </div>
  );
}
